<div class="block">
    <div class="primary">
        <a href="<?= $block->escapeUrl($block->getUrl('update/admin/changename')) ?>" class="action primary"><span>Change Name Again</span></a>
    </div>
</div>

<div class="block">
    <div class="secondary">
        <a href="<?= $block->escapeUrl($block->getUrl('/admin')) ?>" class="action secondary"><span>Go to Dashboard</span></a>
    </div>
</div>
