<form class="form" action="<?= $block->escapeUrl($block->getUrl($block->getChangeNamePost())) ?>" id="change-name-form" method="post" data-hasrequired="* Required Fields" novalidate="novalidate">
    <input name="form_key" type="hidden" value="<?= $block->getFormKey() ?>" />
    <fieldset>
        <div>Here you can change your name.</div>
        <div>
            <label for="first-name">
                <span>First Name</span>
            </label>
            <div>
                <input name="first-name" id="first-name" title="First Name" class="input-text" type="text">
            </div>
        </div>
        <div>
            <label for="last-name"><span>Last Name</span></label>
            <div>
                <input name="last-name" id="last-name" title="Last Name" class="input-text" type="text">
            </div>
        </div>
    </fieldset>
    <div>
        <div>
            <button type="submit" title="Submit" class="action submit primary">
                <span>Submit</span>
            </button>
        </div>
    </div>
</form>